---
title: "Class 05"
author: "Olivia Smith"
date: "2026-09-09"
output:
   html_document:
     toc: true
     toc_float: true
     numbered_sections: true
     code_folding: show
     code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Game 01: Find your seat 

```{r game01}
campus = jsonlite::fromJSON("https://isa401-find-your-seat.vercel.app/campus.json")

dplyr:: glimpse(campus)

fsb = campus[['Farmer']]
fsb$code

names(campus)
```
```{r}
fsb[['floors']]
```

```{r}
sec_floor = fsb$floors[["2"]]
sec_floor$sections

df = sec_floor$rooms
df
df[6,2]
```
### Reading the Excel file

```{r read_excel}
occupation = readxl::read_excel(
  path = "M:\business__intelligence\data\occupation.xlsx", sheet = "Table 1.4", skip = 1
  )

# optional: clean the bottom three rows
occupation= occupation[-c(32,33,34), ] # delete three specific rows, keep all cols (since after the , is empty) --> 1:7
```
## JSON Data
```{r json_data}
json_url = paste0(
  "https://data.cincinnati-oh.gov/",
  "resource/rvmt-pkmq.json?$limit=100")
crashes_json = jsonlite::fromJSON(json_url)
dplyr::glimpse(
  crashes_json[, c("crashdate", "dayofweek",
                   "crashseverity", "age")])
```


## Game 2: Importing Data

```{r}
logins = readr::read_csv("../data/stage1.csv")
log = jsonlite::fromJSON("https://isa401-import-heist.vercel.app/api/stage2?key=smithj31&seat=R2-2&s=A")

stage2 = log$events

```

